### ISSUE TITLE
all liquids have the same texture

### ISSUE THREAD

**Issue by GIKExe** [benbenlaw/skyopolis4#53]
Optifine (any version) uses one texture for all liquids from the KubeJS mod

![image](https://user-images.githubusercontent.com/72767917/186492918-568249c9-d563-413b-a433-c0d90faee2d7.png)
![image](https://user-images.githubusercontent.com/72767917/186493249-98db8665-3538-4df4-aeeb-787701a6261d.png)

**Comment by benbenlaw** [comment]
optifine isnt supported

**Comment by GIKExe** [comment]
Optifine is necessary for normal play

**Comment by benbenlaw** [comment]
Optifine changes parts of Minecrafts rendering engine to make it more performant
most of the time they do this by directly replacing/overwriting code or changing formulas used in computing
the problem is that forge and many mods rely on the original code and functions, so the mods break when they try to use optifine functions
and Optifine doesn't want to make it forge compatible because then they would basically have to revert all their changes
that's why Optifine is fine for vanilla, but sucks for modded 99% of the time
this is also why we don't recommend using fps boosters etc. because they work in the same way as Optifine, they replace code which can break mods

**Comment by GIKExe** [comment]
how can I solve the problem of short freezes and lowering fps to 0 ?

**Comment by benbenlaw** [comment]
amd?

**Comment by IETTCQV** [comment]
nvidia

**Comment by GIKExe** [comment]
Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
